CREATE TABLE career_items (
                              "order" integer,
                              career_id bigint NOT NULL,
                              career_step_id bigint NOT NULL,
                              created_at timestamp(6),
                              id bigint GENERATED BY DEFAULT AS IDENTITY,
                              updated_at timestamp(6),
                              PRIMARY KEY (id),
                              CONSTRAINT idx_ci_career_step_unique UNIQUE (career_id, career_step_id),
                              CONSTRAINT idx_ci_career_order_unique UNIQUE (career_id, "order")
);

CREATE TABLE career_member_versions (
                                        career_member_id bigint NOT NULL,
                                        created_at timestamp(6),
                                        id bigint GENERATED BY DEFAULT AS IDENTITY,
                                        item_id bigint NOT NULL,
                                        event varchar(255) NOT NULL,
                                        item_type varchar(255) NOT NULL,
                                        whodunnit varchar(255),
                                        PRIMARY KEY (id)
);

CREATE TABLE career_members (
                                career_id bigint NOT NULL,
                                created_at timestamp(6),
                                finished_at timestamp(6),
                                id bigint GENERATED BY DEFAULT AS IDENTITY,
                                updated_at timestamp(6),
                                user_id bigint NOT NULL,
                                state varchar(255) NOT NULL,
                                PRIMARY KEY (id),
                                CONSTRAINT idx_cm_user_career_unique UNIQUE (user_id, career_id)
);

CREATE TABLE career_step_members (
                                     career_member_id bigint NOT NULL,
                                     career_step_id bigint NOT NULL,
                                     created_at timestamp(6),
                                     id bigint GENERATED BY DEFAULT AS IDENTITY,
                                     updated_at timestamp(6),
                                     state varchar(255) NOT NULL,
                                     PRIMARY KEY (id),
                                     CONSTRAINT idx_csm_unique UNIQUE (career_member_id, career_step_id)
);

CREATE TABLE career_steps (
                              review_needed boolean,
                              created_at timestamp(6),
                              id bigint GENERATED BY DEFAULT AS IDENTITY,
                              updated_at timestamp(6),
                              description text NOT NULL,
                              locale varchar(255) NOT NULL,
                              name varchar(255) NOT NULL,
                              notification_kind varchar(255),
                              tasks_text text NOT NULL,
                              PRIMARY KEY (id)
);

CREATE TABLE careers (
                         created_at timestamp(6),
                         id bigint GENERATED BY DEFAULT AS IDENTITY,
                         updated_at timestamp(6),
                         description text NOT NULL,
                         locale varchar(255) NOT NULL,
                         name varchar(255) NOT NULL,
                         slug varchar(255) NOT NULL,
                         PRIMARY KEY (id),
                         CONSTRAINT idx_careers_slug UNIQUE (slug)
);

CREATE TABLE countries (
                           created_at timestamp(6),
                           id bigint GENERATED BY DEFAULT AS IDENTITY,
                           updated_at timestamp(6),
                           name varchar(255),
                           PRIMARY KEY (id)
);

CREATE TABLE events (
                        created_at timestamp(6),
                        id bigint GENERATED BY DEFAULT AS IDENTITY,
                        resource_id bigint NOT NULL,
                        updated_at timestamp(6),
                        user_id bigint NOT NULL,
                        kind varchar(255) NOT NULL,
                        locale varchar(255) NOT NULL,
                        resource_type varchar(255) NOT NULL,
                        state varchar(255) NOT NULL,
                        PRIMARY KEY (id)
);

CREATE TABLE impressions (
                             created_at timestamp(6),
                             id bigint GENERATED BY DEFAULT AS IDENTITY,
                             impressionable_id bigint,
                             updated_at timestamp(6),
                             user_id bigint,
                             action_name varchar(255),
                             controller_name varchar(255),
                             impressionable_type varchar(255),
                             ip_address varchar(255),
                             message text,
                             params text,
                             referrer text,
                             request_hash varchar(255),
                             session_hash varchar(255),
                             view_name varchar(255),
                             PRIMARY KEY (id)
);

CREATE TABLE knowledge_articles (
                                    is_published boolean NOT NULL,
                                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                                    published_at timestamp(6),
                                    category varchar(255) NOT NULL,
                                    description text,
                                    image_url varchar(255),
                                    reading_time varchar(255),
                                    title varchar(255) NOT NULL,
                                    PRIMARY KEY (id)
);

CREATE TABLE knowledge_interviews (
                                      is_published boolean NOT NULL,
                                      questions_count integer,
                                      id bigint GENERATED BY DEFAULT AS IDENTITY,
                                      published_at timestamp(6),
                                      category varchar(255) NOT NULL,
                                      description text,
                                      duration varchar(255),
                                      image_url varchar(255),
                                      title varchar(255) NOT NULL,
                                      PRIMARY KEY (id)
);

CREATE TABLE learning_lessons (
                                  duration_minutes integer,
                                  order_number integer NOT NULL,
                                  created_at timestamp(6),
                                  id bigint GENERATED BY DEFAULT AS IDENTITY,
                                  program_id bigint NOT NULL,
                                  updated_at timestamp(6),
                                  content text,
                                  title varchar(255) NOT NULL,
                                  video_url varchar(255),
                                  PRIMARY KEY (id)
);

CREATE TABLE learning_programs (
                                   total_lessons integer,
                                   created_at timestamp(6),
                                   id bigint GENERATED BY DEFAULT AS IDENTITY,
                                   updated_at timestamp(6),
                                   category varchar(255),
                                   description text,
                                   image_url varchar(255),
                                   title varchar(255) NOT NULL,
                                   PRIMARY KEY (id)
);

CREATE TABLE marketing_articles (
                                    display_order integer,
                                    is_published boolean NOT NULL,
                                    reading_time integer,
                                    show_on_homepage boolean,
                                    created_at timestamp(6),
                                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                                    published_at timestamp(6),
                                    updated_at timestamp(6),
                                    author varchar(255),
                                    content text,
                                    home_component_id varchar(255),
                                    image_url varchar(255),
                                    title varchar(255) NOT NULL,
                                    PRIMARY KEY (id)
);

CREATE TABLE marketing_pricing_plans (
                                         discount_percent double precision NOT NULL,
                                         final_price double precision,
                                         original_price double precision NOT NULL,
                                         id bigint GENERATED BY DEFAULT AS IDENTITY,
                                         name varchar(100) NOT NULL,
                                         description varchar(1000) NOT NULL,
                                         PRIMARY KEY (id)
);

CREATE TABLE marketing_reviews (
                                   display_order integer,
                                   is_published boolean NOT NULL,
                                   show_on_homepage boolean NOT NULL,
                                   created_at timestamp(6),
                                   id bigint GENERATED BY DEFAULT AS IDENTITY,
                                   published_at timestamp(6),
                                   updated_at timestamp(6),
                                   author varchar(255) NOT NULL,
                                   avatar_url varchar(255),
                                   content text NOT NULL,
                                   PRIMARY KEY (id)
);

CREATE TABLE marketing_stories (
                                   display_order integer,
                                   is_published boolean NOT NULL,
                                   show_on_homepage boolean,
                                   created_at timestamp(6),
                                   id bigint GENERATED BY DEFAULT AS IDENTITY,
                                   published_at timestamp(6),
                                   updated_at timestamp(6),
                                   content text,
                                   image_url varchar(255),
                                   title varchar(255) NOT NULL,
                                   PRIMARY KEY (id)
);

CREATE TABLE marketing_team (
                                display_order integer,
                                is_published boolean NOT NULL,
                                show_on_homepage boolean NOT NULL,
                                created_at timestamp(6),
                                id bigint GENERATED BY DEFAULT AS IDENTITY,
                                published_at timestamp(6),
                                updated_at timestamp(6),
                                avatar_url varchar(255),
                                first_name varchar(255) NOT NULL,
                                last_name varchar(255) NOT NULL,
                                member_type varchar(255) NOT NULL,
                                position varchar(255) NOT NULL,
                                PRIMARY KEY (id)
);

CREATE TABLE newsletter_settings (
                                     achievements boolean NOT NULL,
                                     comments_replies boolean NOT NULL,
                                     community_news boolean NOT NULL,
                                     course_updates boolean NOT NULL,
                                     marketing_tips boolean NOT NULL,
                                     new_courses boolean NOT NULL,
                                     promotions boolean NOT NULL,
                                     resume_views boolean NOT NULL,
                                     vacancy_matches boolean NOT NULL,
                                     created_at timestamp(6) NOT NULL,
                                     id bigint GENERATED BY DEFAULT AS IDENTITY,
                                     updated_at timestamp(6),
                                     user_id bigint NOT NULL,
                                     PRIMARY KEY (id),
                                     CONSTRAINT idx_newsletter_settings_user_unique UNIQUE (user_id)
);

CREATE TABLE notifications (
                               created_at timestamp(6),
                               id bigint GENERATED BY DEFAULT AS IDENTITY,
                               resource_id bigint NOT NULL,
                               updated_at timestamp(6),
                               user_id bigint NOT NULL,
                               kind varchar(255),
                               resource_type varchar(255) NOT NULL,
                               state varchar(255),
                               PRIMARY KEY (id)
);

CREATE TABLE page_sections (
                               active boolean NOT NULL,
                               id bigint GENERATED BY DEFAULT AS IDENTITY,
                               content varchar(255),
                               created_at varchar(255),
                               page_key varchar(255) NOT NULL,
                               section_key varchar(255) NOT NULL,
                               title varchar(255),
                               updated_at varchar(255),
                               PRIMARY KEY (id),
                               CONSTRAINT idx_page_sections_section_key_unique UNIQUE (section_key)
);

CREATE TABLE resume_answer_comments (
                                        answer_id bigint NOT NULL,
                                        answer_user_id bigint NOT NULL,
                                        created_at timestamp(6),
                                        id bigint GENERATED BY DEFAULT AS IDENTITY,
                                        resume_id bigint NOT NULL,
                                        updated_at timestamp(6),
                                        user_id bigint NOT NULL,
                                        content varchar(255),
                                        PRIMARY KEY (id)
);

CREATE TABLE resume_answer_likes (
                                     answer_id bigint NOT NULL,
                                     created_at timestamp(6),
                                     id bigint GENERATED BY DEFAULT AS IDENTITY,
                                     resume_id bigint NOT NULL,
                                     updated_at timestamp(6),
                                     user_id bigint NOT NULL,
                                     PRIMARY KEY (id),
                                     CONSTRAINT idx_ral_answer_user_unique UNIQUE (answer_id, user_id)
);

CREATE TABLE resume_answers (
                                likes_count integer,
                                created_at timestamp(6),
                                id bigint GENERATED BY DEFAULT AS IDENTITY,
                                resume_id bigint NOT NULL,
                                updated_at timestamp(6),
                                user_id bigint NOT NULL,
                                applying_state varchar(255),
                                content text,
                                PRIMARY KEY (id),
                                CONSTRAINT idx_resume_answers_user_resume_unique UNIQUE (user_id, resume_id)
);

CREATE TABLE resume_comments (
                                 created_at timestamp(6),
                                 id bigint GENERATED BY DEFAULT AS IDENTITY,
                                 resume_id bigint,
                                 updated_at timestamp(6),
                                 user_id bigint,
                                 content varchar(255),
                                 PRIMARY KEY (id)
);

CREATE TABLE resume_educations (
                                   begin_date date,
                                   current boolean,
                                   end_date date,
                                   created_at timestamp(6),
                                   id bigint GENERATED BY DEFAULT AS IDENTITY,
                                   resume_id bigint NOT NULL,
                                   updated_at timestamp(6),
                                   description varchar(255),
                                   faculty varchar(255),
                                   institution varchar(255),
                                   PRIMARY KEY (id)
);

CREATE TABLE resume_works (
                              begin_date date,
                              current boolean,
                              end_date date,
                              created_at timestamp(6),
                              id bigint GENERATED BY DEFAULT AS IDENTITY,
                              resume_id bigint NOT NULL,
                              updated_at timestamp(6),
                              company varchar(255),
                              company_description text,
                              description varchar(255),
                              position varchar(255),
                              PRIMARY KEY (id)
);

CREATE TABLE resumes (
                         answers_count integer NOT NULL,
                         evaluated_ai boolean,
                         impressions_count integer,
                         created_at timestamp(6),
                         id bigint GENERATED BY DEFAULT AS IDENTITY,
                         updated_at timestamp(6),
                         user_id bigint NOT NULL,
                         about_myself text,
                         awards_description text,
                         city varchar(255),
                         contact varchar(255),
                         contact_email varchar(255),
                         contact_phone varchar(255),
                         contact_telegram varchar(255),
                         english_fluency varchar(255),
                         evaluated_ai_state varchar(255),
                         github_url varchar(255),
                         hexlet_url varchar(255),
                         locale varchar(255),
                         name varchar(255) NOT NULL,
                         projects_description text,
                         relocation varchar(255),
                         skills_description text,
                         state varchar(255),
                         summary text,
                         url varchar(255),
                         PRIMARY KEY (id)
);

CREATE TABLE taggings (
                          created_at timestamp(6),
                          id bigint GENERATED BY DEFAULT AS IDENTITY,
                          tag_id bigint,
                          taggable_id bigint,
                          tagger_id bigint,
                          context varchar(255),
                          taggable_type varchar(255),
                          tagger_type varchar(255),
                          tenant varchar(255),
                          PRIMARY KEY (id)
);

CREATE TABLE tags (
                      taggings_count integer,
                      created_at timestamp(6),
                      id bigint GENERATED BY DEFAULT AS IDENTITY,
                      updated_at timestamp(6),
                      name varchar(255),
                      PRIMARY KEY (id),
                      CONSTRAINT idx_tags_name UNIQUE (name)
);

CREATE TABLE user_lessons_progress (
                                       is_completed boolean NOT NULL,
                                       time_spent_minutes integer,
                                       completed_at timestamp(6),
                                       created_at timestamp(6),
                                       id bigint GENERATED BY DEFAULT AS IDENTITY,
                                       lesson_id bigint NOT NULL,
                                       program_progress_id bigint NOT NULL,
                                       started_at timestamp(6),
                                       user_id bigint NOT NULL,
                                       PRIMARY KEY (id)
);

CREATE TABLE user_programs_progress (
                                        completed_lessons integer NOT NULL,
                                        is_completed boolean NOT NULL,
                                        completed_at timestamp(6),
                                        id bigint GENERATED BY DEFAULT AS IDENTITY,
                                        last_activity_at timestamp(6),
                                        last_lesson_id bigint,
                                        program_id bigint NOT NULL,
                                        started_at timestamp(6),
                                        updated_at timestamp(6),
                                        user_id bigint NOT NULL,
                                        PRIMARY KEY (id)
);

CREATE TABLE users (
                       bounced_email boolean,
                       email_disabled_delivery boolean,
                       failed_attempts integer,
                       marked_as_spam boolean,
                       resume_answer_likes_count integer,
                       resume_mail_enabled boolean,
                       sign_in_count integer,
                       token_version bigint NOT NULL DEFAULT 0,
                       confirmation_sent_at timestamp(6),
                       confirmed_at timestamp(6),
                       created_at timestamp(6),
                       current_sign_in_at timestamp(6),
                       id bigint GENERATED BY DEFAULT AS IDENTITY,
                       last_sign_in_at timestamp(6),
                       locked_at timestamp(6),
                       remember_created_at timestamp(6),
                       reset_password_sent_at timestamp(6),
                       updated_at timestamp(6),
                       about varchar(255),
                       confirmation_token varchar(255),
                       current_sign_in_ip varchar(255),
                       email varchar(255),
                       encrypted_password varchar(255),
                       first_name varchar(255),
                       last_name varchar(255),
                       last_sign_in_ip varchar(255),
                       locale varchar(255),
                       provider varchar(255),
                       reset_password_token varchar(255),
                       role varchar(255),
                       state varchar(255),
                       uid varchar(255),
                       unconfirmed_email varchar(255),
                       unlock_token varchar(255),
                       PRIMARY KEY (id),
                       CONSTRAINT idx_users_email UNIQUE (email),
                       CONSTRAINT idx_users_confirmation_token UNIQUE (confirmation_token),
                       CONSTRAINT idx_users_reset_password_token UNIQUE (reset_password_token),
                       CONSTRAINT idx_users_unlock_token UNIQUE (unlock_token)
);

CREATE TABLE vacancies (
                           salary_from integer,
                           salary_to integer,
                           country_id bigint,
                           created_at timestamp(6),
                           creator_id bigint NOT NULL,
                           external_id bigint,
                           id bigint GENERATED BY DEFAULT AS IDENTITY,
                           published_at timestamp(6),
                           updated_at timestamp(6),
                           about_company text,
                           about_project text,
                           cancelation_reason varchar(255),
                           city_name varchar(255),
                           company_name varchar(255),
                           conditions_description text,
                           contact_email varchar(255),
                           contact_name varchar(255),
                           contact_phone varchar(255),
                           contact_telegram varchar(255),
                           employment_type varchar(255),
                           experience_description text,
                           kind varchar(255) NOT NULL,
                           link_for_contact varchar(255),
                           locale varchar(255),
                           location varchar(255),
                           location_of_position varchar(255),
                           position_level varchar(255),
                           programming_language varchar(255),
                           requirements_description text,
                           responsibilities_description text,
                           salary_amount_type varchar(255),
                           salary_currency varchar(255),
                           site varchar(255),
                           state varchar(255),
                           title varchar(255),
                           PRIMARY KEY (id)
);

CREATE TABLE versions (
                          created_at timestamp(6),
                          id bigint GENERATED BY DEFAULT AS IDENTITY,
                          item_id bigint NOT NULL,
                          event varchar(255) NOT NULL,
                          item_type varchar(255) NOT NULL,
                          object text,
                          whodunnit varchar(255),
                          PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens (
                                jti UUID PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                family_id UUID NOT NULL,
                                issued_at TIMESTAMP(6) NOT NULL,
                                expires_at TIMESTAMP(6) NOT NULL,
                                revoked_at TIMESTAMP(6),
                                replaced_by_jti UUID
);

CREATE TABLE stories_stories (
                                 display_order integer,
                                 is_published boolean NOT NULL,
                                 id bigint GENERATED BY DEFAULT AS IDENTITY,
                                 author_name varchar(255) NOT NULL,
                                 avatar_url varchar(2048),
                                 company_name varchar(255),
                                 offer_position varchar(255),
                                 text text NOT NULL,
                                 PRIMARY KEY (id)
);

CREATE INDEX idx_ci_career_id on career_items (career_id);
CREATE INDEX idx_ci_career_step_id on career_items (career_step_id);
CREATE INDEX idx_cmv_item_type on career_member_versions (item_type);
CREATE INDEX idx_cmv_item_id on career_member_versions (item_id);
CREATE INDEX idx_cm_career_id on career_members (career_id);
CREATE INDEX idx_cm_user_id on career_members (user_id);
CREATE INDEX idx_csm_step_id on career_step_members (career_step_id);
CREATE INDEX idx_csm_member_id on career_step_members (career_member_id);
CREATE INDEX idx_events_user_id on events (user_id);
CREATE INDEX idx_events_resource_type on events (resource_type);
CREATE INDEX idx_events_resource_id on events (resource_id);
CREATE INDEX idx_imp_user_id on impressions (user_id);
CREATE INDEX idx_imp_controller on impressions (controller_name);
CREATE INDEX idx_imp_action on impressions (action_name);
CREATE INDEX idx_imp_ip on impressions (ip_address);
CREATE INDEX idx_imp_request_hash on impressions (request_hash);
CREATE INDEX idx_imp_session_hash on impressions (session_hash);
CREATE INDEX idx_imp_impressionable on impressions (impressionable_type, impressionable_id);
CREATE INDEX idx_imp_message on impressions (message);
CREATE INDEX idx_notifications_user_id on notifications (user_id);
CREATE INDEX idx_notifications_resource_type on notifications (resource_type);
CREATE INDEX idx_notifications_resource_id on notifications (resource_id);
CREATE INDEX idx_rac_answer_id on resume_answer_comments (answer_id);
CREATE INDEX idx_rac_answer_user_id on resume_answer_comments (answer_user_id);
CREATE INDEX idx_rac_resume_id on resume_answer_comments (resume_id);
CREATE INDEX idx_rac_user_id on resume_answer_comments (user_id);
CREATE INDEX idx_ral_answer_id on resume_answer_likes (answer_id);
CREATE INDEX idx_ral_resume_id on resume_answer_likes (resume_id);
CREATE INDEX idx_ral_user_id on resume_answer_likes (user_id);
CREATE INDEX idx_resume_answers_resume_id on resume_answers (resume_id);
CREATE INDEX idx_resume_answers_user_id on resume_answers (user_id);
CREATE INDEX idx_rc_resume_id on resume_comments (resume_id);
CREATE INDEX idx_rc_user_id on resume_comments (user_id);
CREATE INDEX idx_resume_educations_resume_id on resume_educations (resume_id);
CREATE INDEX idx_resume_works_resume_id on resume_works (resume_id);
CREATE INDEX idx_resumes_user_id on resumes (user_id);
CREATE INDEX idx_tg_tag_id on taggings (tag_id);
CREATE INDEX idx_tg_taggable_id on taggings (taggable_id);
CREATE INDEX idx_tg_taggable_type on taggings (taggable_type);
CREATE INDEX idx_tg_tagger_id on taggings (tagger_id);
CREATE INDEX idx_tg_context on taggings (context);
CREATE INDEX idx_tg_tenant on taggings (tenant);
CREATE INDEX idx_vacancy_country_id on vacancies (country_id);
CREATE INDEX idx_vacancy_creator_id on vacancies (creator_id);
CREATE INDEX idx_vacancy_external_id on vacancies (external_id);
CREATE INDEX idx_versions_item_type on versions (item_type);
CREATE INDEX idx_versions_item_id on versions (item_id);
CREATE INDEX idx_refresh_tokens_family ON refresh_tokens (family_id, revoked_at);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens (expires_at);

ALTER TABLE career_items
    ADD CONSTRAINT fk_career_items_career
        FOREIGN KEY (career_id) REFERENCES careers;

ALTER TABLE career_items
    ADD CONSTRAINT fk_career_items_career_step
        FOREIGN KEY (career_step_id) REFERENCES career_steps;

ALTER TABLE career_member_versions
    ADD CONSTRAINT fk_career_member_versions_career_member
        FOREIGN KEY (career_member_id) REFERENCES career_members;

ALTER TABLE career_members
    ADD CONSTRAINT fk_career_members_career
        FOREIGN KEY (career_id) REFERENCES careers;

ALTER TABLE career_members
    ADD CONSTRAINT fk_career_members_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE career_step_members
    ADD CONSTRAINT fk_career_step_members_career_member
        FOREIGN KEY (career_member_id) REFERENCES career_members;

ALTER TABLE career_step_members
    ADD CONSTRAINT fk_career_step_members_career_step
        FOREIGN KEY (career_step_id) REFERENCES career_steps;

ALTER TABLE events
    ADD CONSTRAINT fk_events_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE impressions
    ADD CONSTRAINT fk_impressions_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE learning_lessons
    ADD CONSTRAINT fk_learning_lessons_program
        FOREIGN KEY (program_id) REFERENCES learning_programs;

ALTER TABLE newsletter_settings
    ADD CONSTRAINT fk_newsletter_settings_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE notifications
    ADD CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE resume_answer_comments
    ADD CONSTRAINT fk_resume_answer_comments_answer
        FOREIGN KEY (answer_id) REFERENCES resume_answers;

ALTER TABLE resume_answer_comments
    ADD CONSTRAINT fk_resume_answer_comments_answer_user
        FOREIGN KEY (answer_user_id) REFERENCES users;

ALTER TABLE resume_answer_comments
    ADD CONSTRAINT fk_resume_answer_comments_resume
        FOREIGN KEY (resume_id) REFERENCES resumes;

ALTER TABLE resume_answer_comments
    ADD CONSTRAINT fk_resume_answer_comments_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE resume_answer_likes
    ADD CONSTRAINT fk_resume_answer_likes_answer
        FOREIGN KEY (answer_id) REFERENCES resume_answers;

ALTER TABLE resume_answer_likes
    ADD CONSTRAINT fk_resume_answer_likes_resume
        FOREIGN KEY (resume_id) REFERENCES resumes;

ALTER TABLE resume_answer_likes
    ADD CONSTRAINT fk_resume_answer_likes_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE resume_answers
    ADD CONSTRAINT fk_resume_answers_resume
        FOREIGN KEY (resume_id) REFERENCES resumes;

ALTER TABLE resume_answers
    ADD CONSTRAINT fk_resume_answers_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE resume_comments
    ADD CONSTRAINT fk_resume_comments_resume
        FOREIGN KEY (resume_id) REFERENCES resumes;

ALTER TABLE resume_comments
    ADD CONSTRAINT fk_resume_comments_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE resume_educations
    ADD CONSTRAINT fk_resume_educations_resume
        FOREIGN KEY (resume_id) REFERENCES resumes;

ALTER TABLE resume_works
    ADD CONSTRAINT fk_resume_works_resume
        FOREIGN KEY (resume_id) REFERENCES resumes;

ALTER TABLE resumes
    ADD CONSTRAINT fk_resumes_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE taggings
    ADD CONSTRAINT fk_taggings_tag
        FOREIGN KEY (tag_id) REFERENCES tags;

ALTER TABLE user_lessons_progress
    ADD CONSTRAINT fk_user_lessons_progress_lesson
        FOREIGN KEY (lesson_id) REFERENCES learning_lessons;

ALTER TABLE user_lessons_progress
    ADD CONSTRAINT fk_user_lessons_progress_program_progress
        FOREIGN KEY (program_progress_id) REFERENCES user_programs_progress;

ALTER TABLE user_lessons_progress
    ADD CONSTRAINT fk_user_lessons_progress_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE user_programs_progress
    ADD CONSTRAINT fk_user_programs_progress_last_lesson
        FOREIGN KEY (last_lesson_id) REFERENCES learning_lessons;

ALTER TABLE user_programs_progress
    ADD CONSTRAINT fk_user_programs_progress_program
        FOREIGN KEY (program_id) REFERENCES learning_programs;

ALTER TABLE user_programs_progress
    ADD CONSTRAINT fk_user_programs_progress_user
        FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE vacancies
    ADD CONSTRAINT fk_vacancies_country
        FOREIGN KEY (country_id) REFERENCES countries;

ALTER TABLE vacancies
    ADD CONSTRAINT fk_vacancies_creator
        FOREIGN KEY (creator_id) REFERENCES users;

ALTER TABLE refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

